import type { GraphState } from '../graph'

export const dockerTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'Push & Tags',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: ['v*.*.*'],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_docker',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Build and Push Docker',
        jobId: 'docker',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {},
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {
          contents: 'read',
          packages: 'write',
        },
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_docker',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_login',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Log in to GitHub CR',
        mode: 'uses',
        runCommand: '',
        actionRef: 'docker/login-action@v3',
        withParams: {
          registry: 'ghcr.io',
          username: '${{ github.actor }}',
          password: '${{ secrets.GITHUB_TOKEN }}',
        },
        env: {},
        jobNodeId: 'job_docker',
        stepId: 'login',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_meta',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Extract Docker metadata',
        mode: 'uses',
        runCommand: '',
        actionRef: 'docker/metadata-action@v5',
        withParams: {
          images: 'ghcr.io/${{ github.repository }}',
        },
        env: {},
        jobNodeId: 'job_docker',
        stepId: 'meta',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_build_push',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Build and push Docker image',
        mode: 'uses',
        runCommand: '',
        actionRef: 'docker/build-push-action@v5',
        withParams: {
          context: '.',
          push: 'true',
          tags: '${{ steps.meta.outputs.tags }}',
          labels: '${{ steps.meta.outputs.labels }}',
        },
        env: {},
        jobNodeId: 'job_docker',
        stepId: 'build-and-push',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job1',
      source: 'trigger_base',
      target: 'job_docker',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_job_step1',
      source: 'job_docker',
      target: 'step_checkout',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_login',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step2_step3',
      source: 'step_login',
      target: 'step_meta',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step3_step4',
      source: 'step_meta',
      target: 'step_build_push',
      type: 'smoothstep',
      animated: false,
    },
  ],
}
