import type { GraphState } from '../graph'

export const nodejsTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'On Push & PR',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_build',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Build and Test',
        jobId: 'build',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {
          'node-version': ['18.x', '20.x', '22.x'],
        },
        strategyFailFast: true,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {},
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_build',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup Node.js',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/setup-node@v4',
        withParams: {
          'node-version': '${{ matrix.node-version }}',
          cache: 'npm',
        },
        env: {},
        jobNodeId: 'job_build',
        stepId: 'setup-node',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_install',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Install Dependencies',
        mode: 'run',
        runCommand: 'npm ci',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_build',
        stepId: 'install',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_build',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Build',
        mode: 'run',
        runCommand: 'npm run build --if-present',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_build',
        stepId: 'build',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_test',
      type: 'step',
      position: { x: 2400, y: 120 },
      data: {
        kind: 'step',
        label: 'Run Tests',
        mode: 'run',
        runCommand: 'npm test',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_build',
        stepId: 'test',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_build',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_job_step1',
      source: 'job_build',
      target: 'step_checkout',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_install',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step3_step4',
      source: 'step_install',
      target: 'step_build',
      type: 'smoothstep',
      animated: false,
    },
    {
      id: 'e_step4_step5',
      source: 'step_build',
      target: 'step_test',
      type: 'smoothstep',
      animated: false,
    },
  ],
}
