import type { GraphState } from '../graph'

export const phpLaravelTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'Push & PR',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_php',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Laravel Tests',
        jobId: 'laravel-tests',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {},
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {},
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_php',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup PHP',
        mode: 'uses',
        runCommand: '',
        actionRef: 'shivammathur/setup-php@v2',
        withParams: {
          'php-version': '8.2',
          extensions: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, readline, ldap, msgpack, igbinary, redis, swoole, memcached, pcov, xdebug',
          coverage: 'none',
        },
        env: {},
        jobNodeId: 'job_php',
        stepId: 'setup',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_composer',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Install Dependencies',
        mode: 'run',
        runCommand: 'composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_php',
        stepId: 'composer',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_env',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Copy .env',
        mode: 'run',
        runCommand: 'php -r "file_exists(\'.env\') || copy(\'.env.example\', \'.env\');"',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_php',
        stepId: 'env',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_key',
      type: 'step',
      position: { x: 2400, y: 120 },
      data: {
        kind: 'step',
        label: 'Generate key',
        mode: 'run',
        runCommand: 'php artisan key:generate',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_php',
        stepId: 'key',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_test',
      type: 'step',
      position: { x: 2780, y: 120 },
      data: {
        kind: 'step',
        label: 'Execute tests',
        mode: 'run',
        runCommand: 'php artisan test',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_php',
        stepId: 'test',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_php',
      type: 'smoothstep',
    },
    {
      id: 'e_job_step1',
      source: 'job_php',
      target: 'step_checkout',
      type: 'smoothstep',
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_composer',
      type: 'smoothstep',
    },
    {
      id: 'e_step3_step4',
      source: 'step_composer',
      target: 'step_env',
      type: 'smoothstep',
    },
    {
      id: 'e_step4_step5',
      source: 'step_env',
      target: 'step_key',
      type: 'smoothstep',
    },
    {
      id: 'e_step5_step6',
      source: 'step_key',
      target: 'step_test',
      type: 'smoothstep',
    },
  ],
}
