import type { GraphState } from '../graph'

export const pythonDjangoTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'On Push & PR',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_test',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Django Test',
        jobId: 'test',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {
          'python-version': ['3.10', '3.11', '3.12'],
        },
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {},
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_test',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup Python',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/setup-python@v5',
        withParams: {
          'python-version': '${{ matrix.python-version }}',
          cache: 'pip',
        },
        env: {},
        jobNodeId: 'job_test',
        stepId: 'setup',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_deps',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Install Dependencies',
        mode: 'run',
        runCommand: 'python -m pip install --upgrade pip\npip install -r requirements.txt',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_test',
        stepId: 'install',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_test',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Run Django Tests',
        mode: 'run',
        runCommand: 'python manage.py test',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_test',
        stepId: 'test',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_test',
      type: 'smoothstep',
    },
    {
      id: 'e_job_step1',
      source: 'job_test',
      target: 'step_checkout',
      type: 'smoothstep',
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_deps',
      type: 'smoothstep',
    },
    {
      id: 'e_step3_step4',
      source: 'step_deps',
      target: 'step_test',
      type: 'smoothstep',
    },
  ],
}
