import type { GraphState } from '../graph'

export const reactGhPagesTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'Push to main',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_deploy',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Build and Deploy',
        jobId: 'deploy',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {},
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {
          contents: 'write',
        },
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_deploy',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup Node.js',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/setup-node@v4',
        withParams: {
          'node-version': '20',
        },
        env: {},
        jobNodeId: 'job_deploy',
        stepId: 'setup',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_install',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Install Dependencies',
        mode: 'run',
        runCommand: 'npm ci',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_deploy',
        stepId: 'install',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_build',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Build React App',
        mode: 'run',
        runCommand: 'npm run build',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_deploy',
        stepId: 'build',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_deploy',
      type: 'step',
      position: { x: 2400, y: 120 },
      data: {
        kind: 'step',
        label: 'Deploy to GH Pages',
        mode: 'uses',
        runCommand: '',
        actionRef: 'peaceiris/actions-gh-pages@v3',
        withParams: {
          github_token: '${{ secrets.GITHUB_TOKEN }}',
          publish_dir: './dist',
        },
        env: {},
        jobNodeId: 'job_deploy',
        stepId: 'gh_pages',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_deploy',
      type: 'smoothstep',
    },
    {
      id: 'e_job_step1',
      source: 'job_deploy',
      target: 'step_checkout',
      type: 'smoothstep',
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_install',
      type: 'smoothstep',
    },
    {
      id: 'e_step3_step4',
      source: 'step_install',
      target: 'step_build',
      type: 'smoothstep',
    },
    {
      id: 'e_step4_step5',
      source: 'step_build',
      target: 'step_deploy',
      type: 'smoothstep',
    },
  ],
}
