import type { GraphState } from '../graph'

export const rustCargoTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'Push & PR',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_rust',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Rust Cargo Build & Test',
        jobId: 'build',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {},
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {},
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_rust',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup Rust',
        mode: 'uses',
        runCommand: '',
        actionRef: 'dtolnay/rust-toolchain@stable',
        withParams: {
          components: 'clippy, rustfmt',
        },
        env: {},
        jobNodeId: 'job_rust',
        stepId: 'setup',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_cache',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Rust Cache',
        mode: 'uses',
        runCommand: '',
        actionRef: 'Swatinem/rust-cache@v2',
        withParams: {},
        env: {},
        jobNodeId: 'job_rust',
        stepId: 'cache',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_build',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Cargo Build',
        mode: 'run',
        runCommand: 'cargo build --verbose',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_rust',
        stepId: 'build',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_test',
      type: 'step',
      position: { x: 2400, y: 120 },
      data: {
        kind: 'step',
        label: 'Cargo Test',
        mode: 'run',
        runCommand: 'cargo test --verbose',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_rust',
        stepId: 'test',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_rust',
      type: 'smoothstep',
    },
    {
      id: 'e_job_step1',
      source: 'job_rust',
      target: 'step_checkout',
      type: 'smoothstep',
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_cache',
      type: 'smoothstep',
    },
    {
      id: 'e_step3_step4',
      source: 'step_cache',
      target: 'step_build',
      type: 'smoothstep',
    },
    {
      id: 'e_step4_step5',
      source: 'step_build',
      target: 'step_test',
      type: 'smoothstep',
    },
  ],
}
