import type { GraphState } from '../graph'

export const terraformTemplateGraph: GraphState = {
  nodes: [
    {
      id: 'trigger_base',
      type: 'trigger',
      position: { x: 120, y: 120 },
      data: {
        kind: 'trigger',
        label: 'Push to main',
        event: 'push',
        branches: ['main'],
        branchesIgnore: [],
        paths: [],
        pathsIgnore: [],
        tags: [],
        tagsIgnore: [],
        cron: '',
        workflows: [],
        types: [],
      },
      measured: { width: 300, height: 400 },
    },
    {
      id: 'job_tf',
      type: 'job',
      position: { x: 500, y: 120 },
      data: {
        kind: 'job',
        label: 'Terraform Plan & Apply',
        jobId: 'terraform',
        runsOn: 'ubuntu-latest',
        env: {},
        strategyMatrix: {},
        strategyFailFast: false,
        strategyMaxParallel: '',
        timeoutMinutes: '',
        continueOnError: false,
        concurrencyGroup: '',
        concurrencyCancelInProgress: false,
        permissions: {},
        outputs: {},
        defaults: '',
        container: '',
        services: '',
        environment: '',
        environmentUrl: '',
      },
      measured: { width: 300, height: 700 },
    },
    {
      id: 'step_checkout',
      type: 'step',
      position: { x: 880, y: 120 },
      data: {
        kind: 'step',
        label: 'Checkout code',
        mode: 'uses',
        runCommand: '',
        actionRef: 'actions/checkout@v4',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'checkout',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_setup',
      type: 'step',
      position: { x: 1260, y: 120 },
      data: {
        kind: 'step',
        label: 'Setup Terraform',
        mode: 'uses',
        runCommand: '',
        actionRef: 'hashicorp/setup-terraform@v3',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'setup',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_init',
      type: 'step',
      position: { x: 1640, y: 120 },
      data: {
        kind: 'step',
        label: 'Terraform Init',
        mode: 'run',
        runCommand: 'terraform init',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'init',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_fmt',
      type: 'step',
      position: { x: 2020, y: 120 },
      data: {
        kind: 'step',
        label: 'Terraform Format',
        mode: 'run',
        runCommand: 'terraform fmt -check',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'fmt',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_plan',
      type: 'step',
      position: { x: 2400, y: 120 },
      data: {
        kind: 'step',
        label: 'Terraform Plan',
        mode: 'run',
        runCommand: 'terraform plan -no-color',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'plan',
        ifCondition: '',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
    {
      id: 'step_apply',
      type: 'step',
      position: { x: 2780, y: 120 },
      data: {
        kind: 'step',
        label: 'Terraform Apply',
        mode: 'run',
        runCommand: 'terraform apply -auto-approve',
        actionRef: '',
        withParams: {},
        env: {},
        jobNodeId: 'job_tf',
        stepId: 'apply',
        ifCondition: 'github.ref == \'refs/heads/main\' && github.event_name == \'push\'',
        timeoutMinutes: '',
        continueOnError: false,
        workingDirectory: '',
        shell: '',
      },
      measured: { width: 300, height: 600 },
    },
  ],
  edges: [
    {
      id: 'e_trigger_job',
      source: 'trigger_base',
      target: 'job_tf',
      type: 'smoothstep',
    },
    {
      id: 'e_job_step1',
      source: 'job_tf',
      target: 'step_checkout',
      type: 'smoothstep',
    },
    {
      id: 'e_step1_step2',
      source: 'step_checkout',
      target: 'step_setup',
      type: 'smoothstep',
    },
    {
      id: 'e_step2_step3',
      source: 'step_setup',
      target: 'step_init',
      type: 'smoothstep',
    },
    {
      id: 'e_step3_step4',
      source: 'step_init',
      target: 'step_fmt',
      type: 'smoothstep',
    },
    {
      id: 'e_step4_step5',
      source: 'step_fmt',
      target: 'step_plan',
      type: 'smoothstep',
    },
    {
      id: 'e_step5_step6',
      source: 'step_plan',
      target: 'step_apply',
      type: 'smoothstep',
    },
  ],
}
